stages:
  - build
  - test


build:test:iOS:package:
  stage: build
  image: python
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - when: manual
  script: # encode keys before adding it to json! and make sure the environment names match the ones needed for the fastlane configuration!
    - while read -r line; do export FORMATTED_APPLE_API_KEY=$FORMATTED_APPLE_API_KEY$line\\n; done < <(echo $"$APPLE_API_KEY")
    - while read -r line; do export FORMATTED_DISTRIBUTION_KEY=$FORMATTED_DISTRIBUTION_KEY$line\\n; done < <(echo $"$IOS_DISTRIBUTION_PRIVATE_KEY")

    - |
      curl -H "Content-Type:application/json" -H "x-auth-token:$CODEMAGIC_USER_API_KEY" --data \
      '{
        "appId": "6098f09e43c192bee3d14700",
        "workflowId": "react-native-ios",
        "branch": "master",
        "environment":
          {
            "variables":
              {
                "APP_STORE_CONNECT_API_KEY_KEY": "'"$FORMATTED_APPLE_API_KEY"'",
                "APP_STORE_CONNECT_API_KEY_ISSUER_ID": "'"$APP_STORE_CONNECT_ISSUER_ID"'",
                "APP_STORE_CONNECT_API_KEY_KEY_ID": "'"$APP_STORE_CONNECT_KEY_IDENTIFIER"'",
                "IOS_DISTRIBUTION_PRIVATE_KEY": "'"$FORMATTED_DISTRIBUTION_KEY"'",
                "VERSION": "'"$VERSION"'",
                "BUILD_COUNT": "'"$BUILD_COUNT"'"
              }
          }
        }' \
        "https://api.codemagic.io/builds"

