# Check out https://docs.codemagic.io/yaml/building-a-react-native-app/ for more information

workflows:
  
    react-native-ios:
        name: React Native iOS
        max_build_duration: 30
        instance_type: mac_mini
        environment:
            node: latest
            xcode: latest
            cocoapods: default
        scripts:
            - name: set up repository
              script: |
                yarn install
                cd ios
                pod install
        
            - name: initialize keychain
              script: |
                keychain initialize
                         
            - name: set up code-signing
              script: |
                cd ios
                echo "fetch app-store-connect certificates:"
                app-store-connect fetch-signing-files "$BUNDLE_ID" --private-key "$APP_STORE_CONNECT_API_KEY_KEY" --issuer-id "$APP_STORE_CONNECT_API_KEY_ISSUER_ID" --key-id "$APP_STORE_CONNECT_API_KEY_KEY_ID" --certificate-key "$IOS_DISTRIBUTION_PRIVATE_KEY" --type IOS_APP_STORE --create 

                echo "add certs:"
                keychain add-certificates
                
                echo "xcode:"
                xcode-project use-profiles
                security find-identity -v -p codesigning

            #make sure fastlane env is set!
            - name: run fastlane...to the moon!
              script: |
                cp -r fastlane ios
                cd ios

                bundle install 
                gem install fastlane -N
                gem install bundler:1.17.2
                echo -e "installed \n"
                
                bundle update
                bundle update fastlane
                echo -e "updated \n"
      
                bundle exec fastlane ios build_release
                bundle exec fastlane ios flight
                echo -e "done! \n"

